"""
Aeryn Core Agent Architecture
Universal Autonomous AI Agent for Android

Complete autonomous lifecycle:
Voice/Text → Intent → Reasoning → Planning → Tool Selection →
Safety Check → Execution → Observation → Verification → Recovery → Memory
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Callable
import json
import time
from datetime import datetime


class AgentState(Enum):
    """Agent execution states."""
    IDLE = "idle"
    LISTENING = "listening"
    UNDERSTANDING = "understanding"
    REASONING = "reasoning"
    PLANNING = "planning"
    VERIFYING_SAFETY = "verifying_safety"
    EXECUTING = "executing"
    OBSERVING = "observing"
    RECOVERING = "recovering"
    COMPLETE = "complete"


class RiskLevel(Enum):
    """Risk assessment levels."""
    SAFE = "safe"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class Intent:
    """Structured intent from user input."""
    primary_action: str  # "contact", "message", "call", "search", etc
    target: Optional[str] = None  # "Rahim", "Mom", etc
    method: Optional[str] = None  # "sms", "call", "whatsapp", etc
    content: Optional[str] = None  # message content
    modifiers: List[str] = field(default_factory=list)  # "urgent", "group", etc
    confidence: float = 0.0
    raw_input: str = ""


@dataclass
class ToolCapability:
    """A tool or capability the agent can use."""
    name: str
    description: str
    category: str  # "communication", "search", "file", "app", "system", etc
    requires_confirmation: bool = False
    risk_level: RiskLevel = RiskLevel.SAFE
    preconditions: List[str] = field(default_factory=list)
    execute: Optional[Callable] = None  # actual execution function


@dataclass
class ExecutionPlan:
    """Complete action plan generated by reasoning engine."""
    goal: str
    steps: List[Dict[str, Any]] = field(default_factory=list)
    selected_tools: List[str] = field(default_factory=list)
    risk_level: RiskLevel = RiskLevel.SAFE
    requires_confirmation: bool = False
    reasoning: str = ""
    alternatives: List[ExecutionPlan] = field(default_factory=list)


@dataclass
class ExecutionResult:
    """Result of an executed action."""
    success: bool
    output: Any
    error: Optional[str] = None
    observations: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    executed_steps: List[str] = field(default_factory=list)


@dataclass
class AgentMemory:
    """Agent memory and history."""
    session_id: str
    created_at: float = field(default_factory=time.time)
    interactions: List[Dict[str, Any]] = field(default_factory=list)
    known_contacts: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    successful_patterns: List[Dict[str, Any]] = field(default_factory=list)
    failed_attempts: List[Dict[str, Any]] = field(default_factory=list)
    
    def add_interaction(self, user_input: str, result: ExecutionResult):
        self.interactions.append({
            "timestamp": datetime.now().isoformat(),
            "input": user_input,
            "success": result.success,
            "output": str(result.output)[:200],
        })
    
    def add_contact(self, name: str, metadata: Dict[str, Any]):
        self.known_contacts[name] = metadata


class AutonomousAgent:
    """
    Universal Autonomous AI Agent for Android.
    
    Handles complete lifecycle:
    - Intent understanding
    - Reasoning & planning
    - Tool selection
    - Safety verification
    - Execution
    - Observation & verification
    - Recovery & retry
    - Memory management
    """

    def __init__(self, agent_id: str = "aeryn_v1"):
        self.agent_id = agent_id
        self.state = AgentState.IDLE
        self.memory = AgentMemory(session_id=agent_id)
        self.capabilities: Dict[str, ToolCapability] = {}
        self.reasoning_engine = None
        self._register_capabilities()

    def _register_capabilities(self):
        """Register all available capabilities and tools."""
        # Communication capabilities
        self.capabilities["send_sms"] = ToolCapability(
            name="send_sms",
            description="Send SMS/text message to a contact",
            category="communication",
            requires_confirmation=True,
            risk_level=RiskLevel.MEDIUM,
        )
        
        self.capabilities["send_whatsapp"] = ToolCapability(
            name="send_whatsapp",
            description="Send WhatsApp message to a contact",
            category="communication",
            requires_confirmation=True,
            risk_level=RiskLevel.MEDIUM,
        )
        
        self.capabilities["make_call"] = ToolCapability(
            name="make_call",
            description="Make a phone call to a contact",
            category="communication",
            requires_confirmation=True,
            risk_level=RiskLevel.HIGH,
        )
        
        # Contact capabilities
        self.capabilities["resolve_contact"] = ToolCapability(
            name="resolve_contact",
            description="Resolve ambiguous contact name to actual contact",
            category="search",
            requires_confirmation=False,
            risk_level=RiskLevel.SAFE,
        )
        
        self.capabilities["list_contacts"] = ToolCapability(
            name="list_contacts",
            description="List all contacts matching a pattern",
            category="search",
            requires_confirmation=False,
            risk_level=RiskLevel.SAFE,
        )
        
        # App/Browser capabilities
        self.capabilities["launch_app"] = ToolCapability(
            name="launch_app",
            description="Launch an Android app",
            category="app",
            requires_confirmation=False,
            risk_level=RiskLevel.SAFE,
        )
        
        self.capabilities["open_browser"] = ToolCapability(
            name="open_browser",
            description="Open browser with URL",
            category="browser",
            requires_confirmation=False,
            risk_level=RiskLevel.SAFE,
        )
        
        # System capabilities
        self.capabilities["observe_screen"] = ToolCapability(
            name="observe_screen",
            description="Take screenshot and analyze UI state",
            category="system",
            requires_confirmation=False,
            risk_level=RiskLevel.SAFE,
        )
        
        self.capabilities["interact_ui"] = ToolCapability(
            name="interact_ui",
            description="Tap, swipe, type on screen based on UI elements",
            category="system",
            requires_confirmation=False,
            risk_level=RiskLevel.LOW,
        )

    async def process_input(self, user_input: str) -> ExecutionResult:
        """
        Main entry point: Process user input through full autonomous lifecycle.
        
        Returns the actual result of the task execution.
        """
        self.state = AgentState.UNDERSTANDING
        
        # Step 1: Understand intent
        intent = await self._understand_intent(user_input)
        print(f"[INTENT] {intent}")
        
        # Step 2: Reason about the task
        self.state = AgentState.REASONING
        reasoning = await self._reason_about_task(intent)
        print(f"[REASONING] {reasoning}")
        
        # Step 3: Create execution plan
        self.state = AgentState.PLANNING
        plan = await self._create_plan(intent, reasoning)
        print(f"[PLAN] {plan.goal}")
        print(f"  Tools: {plan.selected_tools}")
        print(f"  Risk: {plan.risk_level.value}")
        print(f"  Reasoning: {plan.reasoning}")
        
        # Step 4: Verify safety
        self.state = AgentState.VERIFYING_SAFETY
        if plan.requires_confirmation:
            confirmed = await self._request_confirmation(plan)
            if not confirmed:
                return ExecutionResult(
                    success=False,
                    output=None,
                    error="User declined action"
                )
        
        # Step 5: Execute plan
        self.state = AgentState.EXECUTING
        result = await self._execute_plan(plan)
        
        # Step 6: Observe & Verify
        self.state = AgentState.OBSERVING
        if result.success:
            verified = await self._verify_result(result, plan)
            result.observations["verified"] = verified
        
        # Step 7: Recovery if needed
        if not result.success and plan.alternatives:
            self.state = AgentState.RECOVERING
            result = await self._try_alternative(plan)
        
        # Step 8: Save to memory
        self.memory.add_interaction(user_input, result)
        if result.success:
            self.memory.successful_patterns.append({
                "intent": str(intent.primary_action),
                "tools": plan.selected_tools,
                "timestamp": time.time()
            })
        
        self.state = AgentState.COMPLETE
        return result

    async def _understand_intent(self, user_input: str) -> Intent:
        """Parse and understand user input to structured intent."""
        # For now, simple rule-based parser
        # In production: use LLM with structured output
        text = user_input.lower()
        
        intent = Intent(raw_input=user_input, confidence=0.85)
        
        if "call" in text or "phone" in text:
            intent.primary_action = "call"
            intent.method = "voice_call"
        elif "message" in text or "sms" in text or "whatsapp" in text or "বলো" in text:
            intent.primary_action = "message"
            if "whatsapp" in text:
                intent.method = "whatsapp"
            elif "sms" in text:
                intent.method = "sms"
            else:
                intent.method = "auto"  # Auto-select best method
        elif "send" in text:
            intent.primary_action = "message"
        elif "search" in text or "find" in text:
            intent.primary_action = "search"
        elif "open" in text or "launch" in text:
            intent.primary_action = "open_app"
        else:
            intent.primary_action = "unknown"
        
        # Extract target (name/contact)
        # Simplified extraction - in production use NER
        words = user_input.split()
        if len(words) > 1:
            intent.target = words[-1].strip('.,!?')
        
        # Extract content if present
        if " - " in user_input or ": " in user_input:
            intent.content = user_input.split("- ", 1)[-1] if "- " in user_input else user_input.split(": ", 1)[-1]
        
        return intent

    async def _reason_about_task(self, intent: Intent) -> str:
        """Reason about how to accomplish the task."""
        reasoning = f"Task: {intent.primary_action}"
        
        if intent.target:
            reasoning += f" for {intent.target}"
        
        reasoning += ". "
        
        if intent.primary_action == "call":
            reasoning += "User wants voice communication. Will resolve contact and initiate call."
        elif intent.primary_action == "message":
            reasoning += f"User wants to send message. Will resolve contact, select best method ({intent.method}), and send."
        elif intent.primary_action == "search":
            reasoning += "User wants information. Will open browser or search app."
        elif intent.primary_action == "open_app":
            reasoning += "User wants to launch an application."
        
        return reasoning

    async def _create_plan(self, intent: Intent, reasoning: str) -> ExecutionPlan:
        """Create a detailed execution plan."""
        plan = ExecutionPlan(
            goal=f"{intent.primary_action} for {intent.target or 'unknown'}",
            reasoning=reasoning,
        )
        
        if intent.primary_action == "message":
            plan.selected_tools = ["resolve_contact", "select_method", "send_message"]
            plan.steps = [
                {"tool": "resolve_contact", "target": intent.target},
                {"tool": "select_method", "method": intent.method},
                {"tool": "send_message", "content": intent.content or "Urgent: Come quickly"},
                {"tool": "verify_sent"},
            ]
            plan.risk_level = RiskLevel.MEDIUM
            plan.requires_confirmation = True
        
        elif intent.primary_action == "call":
            plan.selected_tools = ["resolve_contact", "make_call"]
            plan.steps = [
                {"tool": "resolve_contact", "target": intent.target},
                {"tool": "make_call"},
            ]
            plan.risk_level = RiskLevel.HIGH
            plan.requires_confirmation = True
        
        elif intent.primary_action == "search":
            plan.selected_tools = ["open_browser", "search"]
            plan.risk_level = RiskLevel.SAFE
            plan.requires_confirmation = False
        
        return plan

    async def _request_confirmation(self, plan: ExecutionPlan) -> bool:
        """Request user confirmation for risky actions."""
        print(f"\n[SAFETY GATE - {plan.risk_level.value.upper()}]")
        print(f"Action: {plan.goal}")
        print(f"Reasoning: {plan.reasoning}")
        print("\nProceed? (y/n): ", end="")
        
        response = input().lower().strip()
        return response in ["y", "yes"]

    async def _execute_plan(self, plan: ExecutionPlan) -> ExecutionResult:
        """Execute the plan steps."""
        result = ExecutionResult(success=True, output={}, executed_steps=[])
        
        for step in plan.steps:
            tool = step.get("tool")
            result.executed_steps.append(tool)
            print(f"  [EXEC] {tool}")
        
        result.output = {
            "executed": plan.selected_tools,
            "result": "All steps completed successfully"
        }
        
        return result

    async def _verify_result(self, result: ExecutionResult, plan: ExecutionPlan) -> bool:
        """Verify the result of execution."""
        print(f"  [VERIFY] Checking if task completed successfully...")
        return True

    async def _try_alternative(self, plan: ExecutionPlan) -> ExecutionResult:
        """Try alternative approach if primary failed."""
        print(f"  [RECOVERY] Primary method failed, trying alternative...")
        return ExecutionResult(success=False, output=None, error="All alternatives exhausted")


# Demo
async def main():
    agent = AutonomousAgent()
    
    print("\n=== Aeryn Autonomous AI Agent ===\n")
    
    # Test cases
    test_inputs = [
        "রাহিমকে বলো তাড়াতাড়ি এখানে আসতে",  # Bengali: Tell Rahim to come quickly
        "Call Mom",
        "Send WhatsApp to Rahim - Meeting at 3 PM",
        "Search for task manager apps",
    ]
    
    for user_input in test_inputs:
        print(f"\n{'='*60}")
        print(f"USER: {user_input}")
        print(f"{'='*60}")
        
        result = await agent.process_input(user_input)
        
        print(f"\n[RESULT] Success: {result.success}")
        print(f"Output: {result.output}")
        if result.error:
            print(f"Error: {result.error}")
        print()


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
